<?php
/**
 * Gluu_CheckboxesTest.php
 * 
 * @author mat
 * @since 11/22/2014
 *
 * @package wordpress *
 */

class Gluu_CheckboxesTest extends  WP_UnitTestCase {

	/**
	 * o
	 *
	 * @var Gluu_Checkboxes
	 */
	private $o;

	function setUp(){
		parent::setUp();// TODO: Change the autogenerated stub
		$this->o = new Gluu_Checkboxes();

	}


	public function test_swap_tables(){
		global $wpdb;
		$posts = array( $wpdb->posts, $wpdb->postmeta, $wpdb->links );

		$tables = array_keys( $this->o->swap_tables( array( 'posts' ) ) );
		foreach( $tables as $table ){
			$this->assertContains( $table, $posts );
		}
	}


	public function test_custom_tables(){
		global $wpdb;
		$custom = $this->o->custom();
		foreach( $wpdb->tables() as $table ){
			$this->assertNotContains( $table, $custom->tables, "A default table was added to the custom tables list" );
		}
	}
}
 